import { ethers } from "ethers";
import Head from "next/head"
import { useRouter } from "next/router";
import { useState, useEffect } from "react"

import Nft from "../components/nft/nft";
import {alchemy} from "../pages/api/nft"
import styles from "../styles/dashboard.module.css"

export default function Dashboard(){
    const router=useRouter();
    const [balance,setBalance]=useState<string>();
    const [nftData, setNftData]=useState<any>();
    const [address,setAddress]=useState<string>(router.query.address!.toString());
    useEffect(() => {
        window.ethereum.request({
            method:'eth_getBalance', 
            params: [address, 'latest']
        }).then((balance:string) => {
            console.log("here")
            setBalance(ethers.utils.formatEther(balance))
        })
        alchemy.nft.getNftsForOwner(address).then((res)=>{
            setNftData(res)
        })
    })
    

    return(
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>Balance : {balance}</p>
        <section>
            <h2>NFTs</h2>
            <div className={styles.nftlist}>
                {nftData?nftData.ownedNfts.length?nftData.ownedNfts.map((nft:any, index:number)=>{
                    return <Nft key={index} {...nft}/>
                }):
                <div>
                    <h2>No Nft Found</h2>
                </div>:
                <div>
                    <h2>Loding Nfts</h2>
                </div>
                }
            </div>
        </section>
      </main>
      </div>
    )

}